In [2]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter
import sys; 
sys.path.insert(0, 'C:/Users/andre/Documents/GitHub/rotational_diffusion_photophysics')
sys.path.insert(0, 'C:/Users/andre/Documents/GitHub/rotational_diffusion_photophysics/plot')
import rotational_diffusion_photophysics as rdp
from plot_pulse_scheme import plot_pulse_scheme
from plot_sphere_series import plot_sphere_series
from rotational_diffusion_photophysics_models import starss1, starss2, starss3, starss3_detector_signals, isotropic_diffusion

In [10]:
# Rotational diffusion time of target systems
taus =  np.array([1e-6, 3e-6, 10e-6, 30e-6, 100e-6, 300e-6, 1e-3, 3e-3]) 

# STARSS1 signal
# t = np.linspace(-250e-6,1e-3,4000) # Time in a linearly spaced axis
t = np.logspace(-6,3,12) # Time in a log spaced axis
ss = [] # Signals

for tau in taus:
    diffusion = isotropic_diffusion(tau)
    starss3.diffusion = diffusion
    s = starss3_detector_signals(t, experiment=starss3)
    ss.append(s)


C:/Users/andre/Documents/GitHub/rotational_diffusion_photophysics\rotational_diffusion_photophysics.py:843: RuntimeWarning: overflow encountered in exp
  ci = np.matmul(ci0, np.diag(np.exp(L*time[i])))
C:/Users/andre/Documents/GitHub/rotational_diffusion_photophysics\rotational_diffusion_photophysics.py:844: RuntimeWarning: invalid value encountered in matmul
  ci = np.matmul(ci, UTr)


In [12]:
fig2, ax2 = plt.subplots()
fig2.set_dpi(150)
for (s, tau) in zip(ss,taus):
    ax2.plot(t,s)

ax2.set_xlabel('Time (s)')
ax2.set_ylabel('Anisotropy (a.u.)')
ax2.set_xscale('log')
ax2.set_ylim([-0.2, 0.275])
ax2.set_xlim([1e-6, 1e-3])
ax2.legend([str(taus[i]) + ' s' for i, t in enumerate(taus)])
plt.savefig('starss3_anisotropy_multiple_signals')
    

C:\Users\andre\miniconda3\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


ValueError: x and y must have same first dimension, but have shapes (12,) and (2,)

[(array([ 1.56109558,  1.56235512,  1.56235989,  1.56235989,         nan,
                 nan,         nan,         nan,         nan,         nan,
                 nan,         nan]),
  <rotational_diffusion_photophysics.System at 0x1f97ca67348>),
 (array([ 1.55982782,  1.56197851,  1.56237497,  1.56237497,         nan,
                 nan,         nan,         nan,         nan,         nan,
                 nan,         nan]),
  <rotational_diffusion_photophysics.System at 0x1f97ca67348>),
 (array([ 1.55912479,  1.56051785,  1.56233295,  1.56238035,         nan,
                 nan,         nan,         nan,         nan,         nan,
                 nan,         nan]),
  <rotational_diffusion_photophysics.System at 0x1f97ca67348>),
 (array([ 1.55888912,  1.55948291,  1.56153037,  1.56238279,         nan,
                 nan,         nan,         nan,         nan,         nan,
                 nan,         nan]),
  <rotational_diffusion_photophysics.System at 0x1f97ca67348>),
 (ar